---
- name: Install yum packages list
  yum:
    name: "{{ package_list }}"
    state: present

- name: install repo list
  yum:
    name: "{{ repo_list }}"
    state: present
    update_cache: yes


- name: Ensure chrony run
  service:
    name: chronyd
    state: started
    enabled: yes
